"""empty message

Revision ID: b8eab5605f7e
Revises: 2a829f4ce2f8
Create Date: 2021-08-15 19:11:04.174298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eab5605f7e'
down_revision = '2a829f4ce2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
