"""empty message

Revision ID: fb6e83fe7320
Revises: f4b91f61a2d2
Create Date: 2021-08-30 17:56:24.627641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6e83fe7320'
down_revision = 'f4b91f61a2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transhist',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('buy_price', sa.DECIMAL(asdecimal=False), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transhist')
    # ### end Alembic commands ###
