"""empty message

Revision ID: f4b91f61a2d2
Revises: fbd3d3858a07
Create Date: 2021-08-29 20:45:02.564761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b91f61a2d2'
down_revision = 'fbd3d3858a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding', sa.Column('last_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holding', 'last_price')
    # ### end Alembic commands ###
