"""empty message

Revision ID: fbd3d3858a07
Revises: 88f108fc1d57
Create Date: 2021-08-19 18:23:31.145393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd3d3858a07'
down_revision = '88f108fc1d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding')
    # ### end Alembic commands ###
